### ISSUE TITLE
Dakar Desert Rally trainer Unsupported game version (March 2024)

### ISSUE THREAD

**Issue by Dewlapped** [Aldaviva/Trainers#3]
![image](https://github.com/Aldaviva/Trainers/assets/168124884/473017f4-3f73-4859-b433-7539d27464c8)
Dakar Desert Rally trainer doesn't support latest game version:
March 18, 2024 - Hotfix (13722644) update on Steam
[https://store.steampowered.com/news/app/1839940/view/6923793758884093997?l](https://store.steampowered.com/news/app/1839940/view/6923793758884093997)

_I can't drive 55_

**Comment by Aldaviva** [comment]
Thank you for notifying me. I did not realize there was a new version. I used to be subscribed to the game's Steam update RSS feed, but I unsubscribed after the February update because I assumed there would be no more updates.
> This is the end of a memorable journey for the team. We dedicated much of our time into delivering this content and fixes for the issues in Dakar Desert Rally with the hope of ending with a stable product that everyone can enjoy.

I will try to update the trainer for this new version as soon as I get a chance.

**Comment by Aldaviva** [comment]
The Epic Games Store distribution of Dakar Desert Rally still shows `v2.3.0` in the bottom-right corner of the main menu as of 2024-04-25, and therefore I assume Epic Games is providing the older January or February 2024 version of the game.

@Dewlapped Does your Steam distribution of Dakar Desert Rally show a different version number on the game's main menu after the March 18, 2024 update?

**Comment by Dewlapped** [comment]
My steam version also says `v2.3.0` on the menu.

I don't know if the Steam release of the Feb update had a different version number though.

Now I wonder if the EGS version ever got the March hotfix for the G920 crashes.

If you need access to the Steam version I could help.

**Comment by Aldaviva** [comment]
I believe the February Steam version also showed `v2.3.0`, which is a little silly.
Based on the `Wed Mar 13 04:53:58 2024` build time of the `Dakar2Game-Win64-Shipping.exe` executable I have, the Epic Games Store distribution seems to have gotten the March hotfix.

I have updated the trainer for the March Epic release. The speed limit cheat is working on that version now. Let me know if the below dev build works for your March Steam version as well. I am afraid it will not because the `Dakar2Game-Win64-Shipping.exe` file hashes are different, which is both how the trainer determines which memory addresses to write to, and also an indication of whether the binaries are similar enough for those memory addresses to even work in the first place. Therefore, I assume this dev build will still show the "Unsupported game version" error message, as opposed to attaching and erroneously letting you get speed limit penalties.

|Distribution|Build date|`Dakar2Game-Win64-Shipping.exe` SHA-1 hash|
|-|-|-|
|Steam|2024-03-13T05:44:26Z|[`e49a415d77***846ed2f4e5`](https://steamdb.info/depot/1839941/?show_hashes)|
|Epic Games|2024-03-13T11:53:58Z|`59f7e14dc71ed1a044824374f571633e5816c79e`|

**[DakarDesertRallyTrainer.zip](https://github.com/Aldaviva/Trainers/files/15129331/DakarDesertRallyTrainer.zip) dev build**

If this build does not work with your Steam March version, then I may need some help getting access to the Steam version.

**Comment by Dewlapped** [comment]
No luck, still the same error with the new client. You can send a friend request to [my Steam account](https://steamcommunity.com/id/dewlapped/) so I can get you access to the Steam version of Dakar. Thanks.

**Comment by Dewlapped** [comment]
Sent you a message on steam

**Comment by Aldaviva** [comment]
Updated trainer to be compatible with the March 2024 update on both Steam and Epic Games Store. [Released version 1.0.10 of the trainers with this change.](https://github.com/Aldaviva/Trainers/releases/tag/1.0.10)
